name: metamorfose_flutter
description: Aplicativo Metamorfose convertido para Flutter.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  firebase_messaging: ^15.1.1
  # Authentication
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^6.0.4
  # State Management
  flutter_bloc: ^8.1.4
  # Navigation
  go_router: ^13.2.1
  # UI Components
  flutter_svg: ^2.1.0
  google_fonts: ^6.2.1
  flutter_local_notifications: ^17.0.0
  # Maps & Location
  google_maps_flutter: ^2.5.0
  google_maps_flutter_web: ^0.5.4+2
  geolocator: ^10.1.0
  # Networking
  dio: ^5.4.1
  http: ^1.1.0
  # Code Generation
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  # UI
  cupertino_icons: ^1.0.2
  site24x7_flutter_plugin:
    path: local_plugins/site24x7_flutter_plugin/site24x7_flutter_plugin-1.0.0
  flutter_tts: ^3.8.5
  speech_to_text: ^7.0.0
  google_generative_ai: ^0.3.0
  shared_preferences: ^2.2.2
  firebase_storage: ^12.3.3
  screenshot: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  # Code Generation
  build_runner: ^2.4.8
  freezed: ^2.4.7
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/onboarding/
    - assets/images/splashscreen/
    - assets/images/plantsetup/
    - assets/images/auth/
    - assets/images/
    - assets/animations/
    - assets/images/chat/
    - assets/images/home/
    - assets/images/selectionactivity/
  
  fonts:
    - family: DinNext
      fonts:
        - asset: assets/fonts/din_next_regular.otf
        - asset: assets/fonts/din_next_bold.otf
          weight: 700