name: metamorfose_flutter
description: Aplicativo Metamorfose convertido para Flutter.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Firebase
  firebase_core: ^2.27.1
  firebase_auth: ^4.17.9
  cloud_firestore: ^4.15.9
  firebase_messaging: ^14.7.20
  # Authentication
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^6.0.4
  # State Management
  flutter_bloc: ^8.1.4
  # Navigation
  go_router: ^13.2.1
  # UI Components
  flutter_svg: ^2.1.0
  google_fonts: ^6.2.1
  flutter_local_notifications: ^17.0.0
  # Maps & Location
  google_maps_flutter: ^2.5.0
  geolocator: ^10.1.0
  # Networking
  dio: ^5.4.1
  # Code Generation
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  # UI
  cupertino_icons: ^1.0.2
  site24x7_flutter_plugin: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  # Code Generation
  build_runner: ^2.4.8
  freezed: ^2.4.7
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/onboarding/
    - assets/images/splashscreen/
    - assets/images/plantsetup/
    - assets/images/auth/
    - assets/images/
    - assets/animations/
    - assets/images/chat/
    - assets/images/home/
  
  fonts:
    - family: DinNext
      fonts:
        - asset: assets/fonts/din_next_regular.otf
        - asset: assets/fonts/din_next_bold.otf
          weight: 700