name: conversao_flutter
description: Aplicativo Metamorfose convertido para Flutter.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Navegação
  go_router: ^12.1.1
  
  # Gerenciamento de estado
  provider: ^6.0.5
  flutter_bloc: ^8.1.3

  # Material Design e ícones
  cupertino_icons: ^1.0.6
  material_design_icons_flutter: ^7.0.7296
  
  # Animações e UI
  lottie: ^2.6.0
  flutter_svg: ^2.1.0
  google_fonts: ^6.1.0
  cached_network_image: ^3.3.0
  
  # HTTP requests e APIs
  dio: ^5.3.2
  intl: ^0.18.1
  
  # Áudio
  just_audio: ^0.9.35
  audio_waveforms: ^1.0.4
  
  # Maps e Localização
  google_maps_flutter: ^2.5.0
  geolocator: ^10.1.0
  
  # Notificações Locais (sem Firebase por enquanto)
  flutter_local_notifications: ^17.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/onboarding/
    - assets/images/splashscreen/
    - assets/images/plantsetup/
    - assets/images/auth/
    - assets/images/
    - assets/animations/
    - assets/images/chat/
    - assets/images/home/
  
  fonts:
    - family: DinNext
      fonts:
        - asset: assets/fonts/din_next_regular.otf
        - asset: assets/fonts/din_next_bold.otf
          weight: 700
  
  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: assets/fonts/Roboto-Regular.ttf
  #       - asset: assets/fonts/Roboto-Bold.ttf
  #         weight: 700 